# Moderation Bot Configuration
# Advanced moderation bot for Discord servers

[bot]
# Your bot token from Discord Developer Portal
token = "YOUR_BOT_TOKEN_HERE"

# Command prefix
prefix = "!"

# Bot description
description = "Advanced moderation bot powered by MultiCord"

[moderation]
# Auto-moderation settings
auto_mod = true

# Maximum warnings before auto-kick
max_warnings = 3

# Default mute duration in minutes
mute_duration_minutes = 10

# Spam detection
max_message_length = 2000
max_mentions = 5
max_emoji = 20

# Bad words filter (add words to filter)
filter_enabled = false
filtered_words = []

[logging]
# Logging configuration
level = "INFO"
log_moderation_actions = true
log_deleted_messages = true
log_edited_messages = false

[permissions]
# Role names for permission levels
admin_role = "Admin"
moderator_role = "Moderator"
helper_role = "Helper"

[features]
# Enable/disable features
auto_role = false
welcome_messages = false
anti_raid = true
verification = false