# Music Bot Configuration
# Discord music bot for playing audio in voice channels

[bot]
# Your bot token from Discord Developer Portal
token = "YOUR_BOT_TOKEN_HERE"

# Command prefix
prefix = "!"

# Bot description
description = "Music bot powered by MultiCord"

[music]
# Music playback settings
default_volume = 50
max_queue_size = 100
max_song_duration_seconds = 600  # 10 minutes
auto_disconnect_empty = true
auto_disconnect_timeout = 300  # 5 minutes

# Audio quality
bitrate = 128
opus_encoder = true

[features]
# Enable/disable features
playlist_support = true
search_enabled = true
loop_enabled = true
shuffle_enabled = true
bass_boost = false

[permissions]
# Who can use music commands
dj_role = "DJ"
everyone_can_play = true
vote_skip_enabled = true
vote_skip_percentage = 50

[logging]
level = "INFO"